### PR TITLE
Join Request

### PR DESCRIPTION
**Pull request by noblechap**

### CODE REVIEW

**Comment by yonguelink** [comment]
Thanks for the interest in my school-related work @noblechap, however, as written in the README:

> My school work is under a private repository, if you want to see them, give me your GitHub username and **a reason why** you want to see them

So, why do you want to see my school work? It'd also help to know who you are - your GitHub history has nothing in it except that it was created in 2018.

If this is related to work, I believe you already have my email adress - please continue this conversation via that email.

Thank you for understanding :)

**Comment by pinkamena1212** [comment]
Hey,

I hope you're doing well! I wanted to reach out and introduce myself. I'm Alison, and I'm currently a student at CEGEP, wrapping up my technical program in computer science. I'm eager to continue my journey in the field by pursuing a computer science degree at the university level.

As I've been exploring various university programs, I stumbled upon your GitHub profile, where I noticed you've shared some interesting projects related to your computer science studies. I have to say, I'm quite intrigued by what I've seen so far!

I'm reaching out today to ask if it would be possible for me to gain access to your GitHub projects. My main goal is to get a better understanding of the kinds of projects and skills that university-level computer science programs delve into. I want to make it clear that I'm not looking to copy your work or use it without permission in any way if I decide to pursue the same university program that you did.

If you'd be open to granting me access, it would be a tremendous help in making an informed decision about which university program to pursue. Of course, I'd be more than willing to respect any privacy or confidentiality settings you have in place for your GitHub account. If needed, I can even sign any agreements you prefer to ensure the security of your data.

I appreciate your time and consideration in this matter. Thanks for potentially offering me insights into the world of computer science at the university level.

Cheers,

Alison

**Comment by yonguelink** [comment]
@noblechap if I haven't heard back from you by monday the 25th, I'll consider this request moot. If this happens but you still are interested, open an issue with the answer to my question and I'll reconsider.

**Comment by noblechap** [comment]
Hello, I am a self taught programmer currently looking to join a computer science bachelor's degree. Just trying to see what kind of work is done in those programs to help my decision. You are welcome to deny my request if my reason isn't what you are looking for. Regards

**Comment by yonguelink** [comment]
Are you two, @noblechap & @pinkamena1212, related in any way? It seems odd to me that the 2 of you came at the same time w/ basically the same request with the (almost) same reason.

**Pull request closed without merging**
